// Generates parity/fixture.json from this repo's core — the single assertion
// surface every moon-mansions port must satisfy (Raycast, Chrome, Swift).
// Other ports vendor this file and check themselves against it, so a change
// here that is not carried across fails a test instead of drifting silently.
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { getMoonInfo } from "../src/moon.ts";

// Resolve the repo root from this script's own path, so the output lands in
// the repo whether run through tsx or bundled to a temp file by esbuild.
const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE.includes("/scripts/") ? join(HERE, "..") : process.cwd());

// Fixed UTC instants, chosen by scanning 2026 at 3-hourly steps so that every
// VOC branch and every Ptolemaic aspect is represented. Between them they cover
// waxing and waning, all eight phase names, both VOC lengths, and all five
// aspects — so a regression in any of those paths changes a recorded value
// rather than passing unnoticed.
const CASES = [
  "2026-01-01T00:00:00Z", // applying square Saturn, 30.7h out
  "2026-01-02T15:00:00Z", // applying opposition Venus
  "2026-01-02T09:00:00Z", // short VOC
  "2026-01-03T15:00:00Z", // applying conjunction Jupiter
  "2026-01-04T00:00:00Z", // applying trine Saturn
  "2026-01-04T15:00:00Z", // long VOC (50.2h to ingress)
  "2026-01-08T03:00:00Z", // applying sextile Jupiter
  "2026-04-08T18:45:00Z", // last quarter
  "2026-07-21T22:05:00Z", // first quarter
  "2026-10-04T07:10:00Z", // deep VOC whose ingress lands next day
  "2025-11-02T09:15:00Z", // waxing gibbous
  "2026-02-27T14:20:00Z", // waxing gibbous
];

const round = (x: number, p = 4): number => Number(x.toFixed(p));

const cases = CASES.map((iso) => {
  const when = new Date(iso);
  const m = getMoonInfo(when);
  return {
    at: iso,
    phaseName: m.phaseName,
    illumPct: round(m.illumPct, 2),
    zodiac: m.zodiac,
    deg: m.deg,
    signMotion: m.signMotion,
    siderealZodiac: m.siderealZodiac,
    siderealDeg: m.siderealDeg,
    mansion: m.mansion.name,
    mansionNum: m.mansion.num,
    nakshatra: m.nakshatra.name,
    xiu: m.xiu.name,
    xiuAnimal: m.xiu.animal,
    xiuEmoji: m.xiu.emoji,
    voc: {
      isVoc: m.voc.isVoc,
      // NaN is not valid JSON; the no-ingress branch records null.
      ingressInHours: Number.isFinite(m.voc.ingressInHours) ? round(m.voc.ingressInHours, 3) : null,
      nextSign: m.voc.nextSign,
      nextAspect: m.voc.nextAspect,
    },
    // The label is time- and locale-dependent, so the ports assert the
    // weekday-qualified end date instead of a rendered string.
    vocEndUtc: m.voc.isVoc && Number.isFinite(m.voc.ingressInHours)
      ? new Date(when.getTime() + m.voc.ingressInHours * 3600e3).toISOString().slice(0, 16)
      : null,
    planets: m.planets.map((p) => ({ name: p.name, sign: p.sign, deg: p.deg, motion: p.motion })),
  };
});

const fixture = {
  $comment:
    "GENERATED by moon-mansions/scripts/gen-parity.mts — do not hand-edit. " +
    "Regenerate after any core change, then port the delta to every other port.",
  tolerance: { deg: 0.05, hours: 0.05 },
  cases,
};

const out = join(ROOT, "parity", "fixture.json");
mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, JSON.stringify(fixture, null, 2) + "\n");
console.log(`wrote ${out} (${cases.length} cases)`);