#!/usr/bin/env bash
# Installs the cross-repo parity gate as a pre-commit hook in all three
# moon-mansions ports. Safe to re-run; it rewrites only our own hook block.
# Hooks are not versioned, so every clone runs this once after setup.
set -uo pipefail

CORE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SIBLINGS=("$CORE" "$CORE/../moon-mansions-chrome" "$CORE/../moon-mansions-mac")

MARKER="# >>> moon-mansions cross-repo parity >>>"
# The shebang is emitted separately, so BODY must not contain one — otherwise
# every run leaves a duplicate above the marker.
BODY='# >>> moon-mansions cross-repo parity >>>
# Generated by moon-mansions/scripts/install-hooks.sh — do not edit.
# Verifies this port still agrees with the canonical TypeScript core.
set -uo pipefail
GATE="'"$CORE"'/scripts/parity-check.sh"
if [ -x "$GATE" ]; then
  "$GATE" || { echo; echo "  cross-port parity FAILED — commit blocked."; echo "  Fix this port, or run: npm run parity:regen   (core repo)"; exit 1; }
fi
# <<< moon-mansions cross-repo parity <<<
'

for repo in "${SIBLINGS[@]}"; do
  [[ -d "$repo/.git" ]] || { echo "skip $repo (not a git repo)"; continue; }
  hook="$repo/.git/hooks/pre-commit"
  mkdir -p "$(dirname "$hook")"
  if [[ -f "$hook" ]] && ! grep -q "$MARKER" "$hook"; then
    echo "refusing to overwrite existing $hook (no parity marker) — merge manually"
    continue
  fi
  if [[ -f "$hook" ]]; then
    # Keep the user's own logic (everything outside our block), then re-emit
    # exactly one shebang and drop leading blank lines. Marker-scoped and
    # shebang-normalising, so re-running is idempotent instead of stacking.
    awk '
      /cross-repo parity >>/ { skip = 1; next }
      skip && /cross-repo parity <</ { skip = 0; next }
      skip { next }
      /^#!\/usr\/bin\/env bash$/ { next }
      { lines[++n] = $0 }
      END {
        start = 1
        while (start <= n && lines[start] ~ /^[[:space:]]*$/) start++
        for (i = start; i <= n; i++) print lines[i]
      }
    ' "$hook" > "$hook.tmp"
    { printf '%s\n' '#!/usr/bin/env bash'; cat "$hook.tmp"; } > "$hook.2"
    mv "$hook.2" "$hook"
    rm -f "$hook.tmp"
  fi
  printf '%s\n' "$BODY" >> "$hook"
  chmod +x "$hook"
  echo "installed pre-commit hook in $(basename "$repo")"
done